GET http://localhost:5000/


### Get all Users
GET http://localhost:5000/api/users


### Add User
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "name": "Anuj Sharma",
    "phoneNumber": "7726062540",
    "IMEI": "1646155",
    "latitude": "23.432521",
    "longitude": "73.432515",
    "password": "password"
}


### Login User
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "phoneNumber": "7597917007",
    "password": "password"
}


### Get all Complaints

GET http://localhost:5000/api/complaints
Authorization: 


### Get all Fake Complaints

GET http://localhost:5000/api/complaints?fake=true
Authorization: 


### Get all Solved Complaints

GET http://localhost:5000/api/complaints?solved=true
Authorization: 


### Get a Complaint by id

GET http://localhost:5000/api/complaints/5ea162d233b3e93fd0ecb814
Authorization: 


### Change Status of a complaint
CHECKOUT http://localhost:5000/api/complaints/5ea162d233b3e93fd0ecb814
Authorization: 
Content-Type: application/json

{
    "reason": "lol2"
}


### Delete a Complaint
DELETE http://localhost:5000/api/complaints/5ea162d233b3e93fd0ecb814
Authorization: 
Content-Type: application/json

{
    "reason": "lol"
}


### Restore Complaint
PUT http://localhost:5000/api/complaints/5ea162d233b3e93fd0ecb814
Authorization: 


### Add Complaint

POST http://localhost:5000/api/complaints
Content-Type: application/json

{
    "authorization": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoie1wiX2lkXCI6XCI1ZjFlYTU1Yzk2YzFmMDIyZTA2MzY5OTNcIixcIm5hbWVcIjpcIkFudWogU2hhcm1hXCIsXCJwaG9uZU51bWJlclwiOjc3MjYwNjI1NDAsXCJJTUVJXCI6MTY0NjE1NSxcImxhdGl0dWRlXCI6MjMuNDMyNTIxLFwibG9uZ2l0dWRlXCI6NzMuNDMyNTE1LFwicGFzc3dvcmRcIjpcIiQyYSQxMCRXQ0NmanprN3RjTlRKcUlCQ2l3SUpPMkhaUTlDRDQvUlF4ckdhbUNBdDFhMnNhdXhUeEVVLlwiLFwiY3JlYXRlZEF0XCI6XCIyMDIwLTA3LTI3VDA5OjU4OjUyLjYzNlpcIixcInVwZGF0ZWRBdFwiOlwiMjAyMC0wNy0yN1QwOTo1ODo1Mi42MzZaXCIsXCJfX3ZcIjowfSIsImlhdCI6MTU5NTg0MzkzMn0.nbXoDRVOg19Z2h-KvsZygnbK7lvFxruRQzjkQ1pBxSw",
    "victimName": "Test",
    "complaint": "Testing",
    "crimeCategory":"Theft",
    "age":"21",
    "gender": "M",
    "iLatitude":"23.453265",
    "iLongitude":"73.432515",
    "landmark":"Techno India NJR",
    "dateOfIncident":"12-07-2020",
    "timeOfIncident":"09:00 AM"
}


### Get all Regions
GET http://localhost:5000/api/regions


### Dashboard Register
POST http://localhost:5000/api/dashboard/register
Authorization: 
Content-Type: application/json

{
    "username": "jawarmines",
    "region": "JAWAR MINES",
    "password": "password"
}


### Dashboard Login
POST http://localhost:5000/api/dashboard/login
Content-Type: application/json

{
    "username": "superadmin",
    "password": "password"
}

### Get all dashboard users
GET http://localhost:5000/api/dashboard/users
Authorization: 


### Send Complaint on whatsapp
POST http://localhost:5000/api/whatsapp
Content-Type: application/json

{
    "complaintId": "5ea181edce8d983b186c7ff5"
}


### get alert

GET http://localhost:5000/api/status
id:5f0a9b2c1082d539bc7aa4b7

 
