GET http://localhost:5000/


### Get all Users
GET http://localhost:5000/api/users


### Add User
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "name": "Bhavit Kanthalia",
    "phoneNumber": "7597917007",
    "IMEI": "1646154",
    "latitude": "23.432521",
    "longitude": "73.432515",
    "password": "password"
}


### Login User
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "phoneNumber": "7597917007",
    "password": "password"
}


### Get all Complaints

GET http://localhost:5000/api/complaints
Authorization: 


### Get all Fake Complaints

GET http://localhost:5000/api/complaints?fake=true


### Get all Solved Complaints

GET http://localhost:5000/api/complaints?solved=true


### Get a Complaint by id

GET http://localhost:5000/api/complaints/5e9eb689ac6ba51a3048fb98


### Change Status of a complaint
CHECKOUT http://localhost:5000/api/complaints/5e9ec2338bcc113f7496c2f3


### Delete a Complaint
DELETE http://localhost:5000/api/complaints/5e9eb689ac6ba51a3048fb98


### Add Complaint

POST http://localhost:5000/api/complaints
Content-Type: application/json

{
    "authorization": "",
    "victimName": "Pappu",
    "complaint": "Child Labor",
    "age":"24",
    "gender": "M",
    "iLatitude":"23.453265",
    "iLongitude":"73.432515"
}


### Get all Regions
GET http://localhost:5000/api/regions


### Dashboard Register
POST http://localhost:5000/api/dashboard/register
Authorization: 
Content-Type: application/json

{
    "username": "jawarmines",
    "region": "JAWAR MINES",
    "password": "password"
}


### Dashboard Login
POST http://localhost:5000/api/dashboard/login
Content-Type: application/json

{
    "username": "superadmin",
    "password": "password"
}

### Get all dashboard users
GET http://localhost:5000/api/dashboard/users
Authorization: 


### Delete dashboard admin
DELETE http://localhost:5000/api/dashboard/users/5ea039588eb71f18d075b3c4
Authorization: 


###
