GET http://localhost:5000/


### Get all Users
GET http://localhost:5000/api/users


### Add User
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "name": "Mendak Sharma",
    "email": "anujsharma11098@gmail.com",
    "phoneNumber": "7726062541",
    "IMEI": "1646155",
    "latitude": "23.432521",
    "longitude": "73.432515",
    "password": "password"
}


### Login User
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "anujsharma11098@gmail.com",
    "password": "password"
}


### Get all Complaints

GET http://localhost:5000/api/complaints
Authorization: 


### Get all Fake Complaints

GET http://localhost:5000/api/complaints?fake=true
Authorization: 


### Get all Solved Complaints

GET http://localhost:5000/api/complaints?solved=true
Authorization: 


### Get a Complaint by id

GET http://localhost:5000/api/complaints/5ea162d233b3e93fd0ecb814
Authorization: 


### Change Status of a complaint
CHECKOUT http://localhost:5000/api/complaints/5ea162d233b3e93fd0ecb814
Authorization: 
Content-Type: application/json

{
    "reason": "lol2"
}


### Delete a Complaint
DELETE http://localhost:5000/api/complaints/5ea162d233b3e93fd0ecb814
Authorization: 
Content-Type: application/json

{
    "reason": "lol"
}


### Restore Complaint
PUT http://localhost:5000/api/complaints/5ea162d233b3e93fd0ecb814
Authorization: 


### Add Complaint

POST http://localhost:5000/api/complaints
Content-Type: application/json

{
    "authorization": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoie1wiX2lkXCI6XCI2MDFhNmNjNWUyNTcwZTQ2ZjQ4NzI4NzdcIixcIm5hbWVcIjpcIkFudWogU2hhcm1hXCIsXCJwaG9uZU51bWJlclwiOjc3MjYwNjI1NDAsXCJJTUVJXCI6MTY0NjE1NSxcImxhdGl0dWRlXCI6MjMuNDMyNTIxLFwibG9uZ2l0dWRlXCI6NzMuNDMyNTE1LFwicGFzc3dvcmRcIjpcIiQyYSQxMCRZNWZyY0VSTnRNVFhpaTNIdFhlejguZk5mSUE0cGg3MXdFbERUNC5hZXVzdTJIenFNZVlvdVwiLFwiY3JlYXRlZEF0XCI6XCIyMDIxLTAyLTAzVDA5OjI4OjM3LjA1MVpcIixcInVwZGF0ZWRBdFwiOlwiMjAyMS0wMi0wM1QwOToyODozNy4wNTFaXCIsXCJfX3ZcIjowfSIsImlhdCI6MTYxMjM0NDUzM30.tX4c3Vyff4-as1szPieUM-bfMYrgduWuJ5AiuWkQPnM",
    "victimName": "Anuj Sharma",
    "complaint": "Molestation",
    "crimeCategory":"Molestation",
    "age":"21",
    "gender": "M",
    "iLatitude":"24.584286",
    "iLongitude":"73.692635",
    "landmark":"Mere ghr pr",
    "dateOfIncident":"03-02-2021",
    "timeOfIncident":"03:00 PM"
}


### Get all Regions
GET http://localhost:5000/api/regions


### Dashboard Register
POST http://localhost:5000/api/dashboard/register
Authorization: 
Content-Type: application/json

{
    "username": "jawarmines",
    "region": "JAWAR MINES",
    "password": "password"
}


### Dashboard Login
POST http://localhost:5000/api/dashboard/login
Content-Type: application/json

{
    "username": "superadmin",
    "password": "password"
}

### Get all dashboard users
GET http://localhost:5000/api/dashboard/users
Authorization: 


### Send Complaint on whatsapp
POST http://localhost:5000/api/whatsapp
Content-Type: application/json
Authorization: 


{
    "complaintId": "5f284a5b7ba5720017117f26"
}


### get alert

GET http://localhost:5000/api/status
id:5f0a9b2c1082d539bc7aa4b7

 
### Send Remark
POST http://localhost:5000/api/remark
Content-Type: application/json

{
    "complaintId": "5f227393d1663a00176f4d42",
    "remark":"testing"
}

### Get Remark
GET http://localhost:5000/api/remark

### Send SOS
POST http://localhost:5000/api/sos
Content-Type: application/json

{
        "authorization": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoie1wiX2lkXCI6XCI1ZjFlYTU1Yzk2YzFmMDIyZTA2MzY5OTNcIixcIm5hbWVcIjpcIkFudWogU2hhcm1hXCIsXCJwaG9uZU51bWJlclwiOjc3MjYwNjI1NDAsXCJJTUVJXCI6MTY0NjE1NSxcImxhdGl0dWRlXCI6MjMuNDMyNTIxLFwibG9uZ2l0dWRlXCI6NzMuNDMyNTE1LFwicGFzc3dvcmRcIjpcIiQyYSQxMCRXQ0NmanprN3RjTlRKcUlCQ2l3SUpPMkhaUTlDRDQvUlF4ckdhbUNBdDFhMnNhdXhUeEVVLlwiLFwiY3JlYXRlZEF0XCI6XCIyMDIwLTA3LTI3VDA5OjU4OjUyLjYzNlpcIixcInVwZGF0ZWRBdFwiOlwiMjAyMC0wNy0yN1QwOTo1ODo1Mi42MzZaXCIsXCJfX3ZcIjowfSIsImlhdCI6MTU5NTg0MzkzMn0.nbXoDRVOg19Z2h-KvsZygnbK7lvFxruRQzjkQ1pBxSw",
     "iLatitude":"23.453265",
    "iLongitude":"73.432515"
}

### Get SOS
GET http://localhost:5000/api/sos


###
GET http://localhost:5000/api/charts
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoie1wiX2lkXCI6XCI1ZjBjNmFhM2RhYTUzZjMxNDAzNWM5NjRcIixcInVzZXJuYW1lXCI6XCJzdXBlcmFkbWluXCIsXCJwYXNzd29yZFwiOlwiJDJhJDEwJGwuLngwbEN2QlJxWnZHd2twbWdaTmV1V1BmV2paY3hmNmFHUndqYzFyS3EzZGR2bGQvM21xXCIsXCJyZWdpb25cIjpcImFsbFwiLFwicm9sZVwiOlwic3VwZXJhZG1pblwiLFwiY3JlYXRlZEF0XCI6XCIyMDIwLTA3LTEzVDE0OjA3OjMxLjYwMVpcIixcInVwZGF0ZWRBdFwiOlwiMjAyMC0wNy0xM1QxNDowNzozMS42MDFaXCIsXCJfX3ZcIjowfSIsImlhdCI6MTU5NjM4NTUzNn0.2efnIH5jfRwL9mz2PzyqILRsQdAncbrYeTYCyWOv3Lc


###
POST http://localhost:5000/api/alert/
Content-Type: application/json

{
    "title": "Lockdown Timing",
    "alertMsg": "5:00 am to 5:00 pm"
}

###
POST http://localhost:5000/api/feedback/
Content-Type: application/json

{
    "rating": "3.5",
    "feedback": "good to see you"
}
